"""
7Scenes DataLoader for RAFT-Pose training.

Reads a JSON config file (generated by scripts/generate_pairs.py) and provides
PyTorch Dataset / DataLoader for training and validation.

Each sample returns:
    image:          (3, H, W) float32 — frame A RGB, normalized to [0, 1]
    depth:          (4, H, W) float32 — frame B
                    Ch 0:   raw depth in meters (used for depth projection)
                    Ch 1:3: frame B RGB (normalized [0,1]), encoded by the
                            shared image_encoder for RGB<->RGB matching
    intrinsic_rgb:  (3, 3) float32 RGB camera intrinsic matrix
    intrinsic_depth:(3, 3) float32 depth camera intrinsic matrix
    gt_pose:        (7,) float32 relative pose [qw, qx, qy, qz, tx, ty, tz]
                    T_rel = T_img^(-1) @ T_depth
    sample_id:      int
"""

import os
import json
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, ConcatDataset
from pathlib import Path
from PIL import Image


class SevenScenesDataset(Dataset):
    """
    7Scenes dataset for RAFT-Pose training.

    Loads paired (RGB image, depth map) samples with ground-truth relative pose
    computed from absolute camera poses.
    """

    def __init__(
        self,
        config_path: str,
        split: str = "train",
        image_size: tuple = None,
        depth_scale: float = None,
        augment: bool = False,
        normalize_image: bool = True,
    ):
        """
        Args:
            config_path: Path to JSON config file generated by generate_pairs.py
            split: 'train' or 'val'
            image_size: Override image size as (H, W). If None, use config value.
                        Recommended: (256, 320) or smaller for manageable memory.
            depth_scale: Override depth scale. If None, use config value.
            augment: Whether to apply data augmentation
            normalize_image: Whether to normalize images to [0, 1]
        """
        super().__init__()

        with open(config_path, 'r') as f:
            config = json.load(f)

        self.dataset_root = config["dataset_root"]
        self.split = split
        self.augment = augment
        self.normalize_image = normalize_image

        # Camera intrinsics
        intr = config["camera_intrinsics"]

        # Original image size from config (intrinsics correspond to this resolution)
        self.orig_image_size = tuple(config.get("image_size", [480, 640]))

        # Determine target image size
        if image_size is not None:
            self.image_size = tuple(image_size)
        else:
            self.image_size = self.orig_image_size

        # Scale intrinsics if target size differs from original
        if self.image_size != self.orig_image_size:
            sx = self.image_size[1] / self.orig_image_size[1]  # W_target / W_orig
            sy = self.image_size[0] / self.orig_image_size[0]  # H_target / H_orig
            fx, fy = intr["fx"] * sx, intr["fy"] * sy
            cx, cy = intr["cx"] * sx, intr["cy"] * sy
        else:
            fx, fy, cx, cy = intr["fx"], intr["fy"], intr["cx"], intr["cy"]

        self.intrinsic_matrix = torch.tensor([
            [fx, 0.0, cx],
            [0.0, fy, cy],
            [0.0, 0.0, 1.0],
        ], dtype=torch.float32)

        # Depth scale: convert raw depth values to meters
        if depth_scale is not None:
            self.depth_scale = depth_scale
        else:
            self.depth_scale = config.get("depth_scale", 0.001)

        # Load samples
        if split == "train":
            self.samples = config["train_samples"]
        elif split == "val":
            self.samples = config["val_samples"]
        else:
            raise ValueError(f"Unknown split: {split}")

        if not self.samples:
            raise ValueError(f"No samples found for split '{split}' in {config_path}")

        print(f"[SevenScenesDataset] {os.path.basename(config_path)} split={split}, "
              f"samples={len(self.samples)}, "
              f"orig={self.orig_image_size}→{self.image_size}, "
              f"K=({fx:.1f}, {fy:.1f}, {cx:.1f}, {cy:.1f}), "
              f"depth_scale={self.depth_scale}")

    def __len__(self):
        return len(self.samples)

    def _load_image(self, scene, seq, frame):
        """Load frame A RGB image as float32 tensor (3, H, W), normalized to [0, 1]."""
        path = os.path.join(self.dataset_root, scene, seq, f"color_{frame}.png")
        img = Image.open(path).convert("RGB")
        img = img.resize((self.image_size[1], self.image_size[0]), Image.BILINEAR)
        arr = np.array(img, dtype=np.float32)  # (H, W, 3)
        if self.normalize_image:
            arr = arr / 255.0
        return torch.from_numpy(arr).permute(2, 0, 1)  # (3, H, W)

    def _load_depth(self, scene, seq, frame):
        """Load frame B as 4-channel float32 tensor (4, H, W) = [raw_depth, R, G, B].

        Ch 0: raw depth in meters (clamped to [0, 10]) — used for depth projection.
        Ch 1:3: frame B's RGB (normalized [0,1]) — encoded by the SHARED image
              encoder for RGB<->RGB appearance matching (frame A is also RGB).
              Packing depth + RGB in one tensor keeps the dataloader interface
              unchanged; the model slices depth[:, 0:1] for projection and
              depth[:, 1:4] for the encoder.
        """
        # Raw depth (meters)
        dpath = os.path.join(self.dataset_root, scene, seq, f"depth_{frame}.png")
        depth = Image.open(dpath)
        depth = depth.resize((self.image_size[1], self.image_size[0]), Image.NEAREST)
        darr = np.array(depth, dtype=np.float32) * self.depth_scale
        darr = np.clip(darr, 0.0, 10.0)

        # Frame B RGB (for the shared encoder)
        cpath = os.path.join(self.dataset_root, scene, seq, f"color_{frame}.png")
        cimg = Image.open(cpath).convert("RGB")
        cimg = cimg.resize((self.image_size[1], self.image_size[0]), Image.BILINEAR)
        carr = np.array(cimg, dtype=np.float32)  # (H, W, 3)
        if self.normalize_image:
            carr = carr / 255.0

        # Stack: (4, H, W) = [raw_depth, R, G, B]
        return torch.from_numpy(np.stack([darr, carr[..., 0], carr[..., 1], carr[..., 2]], axis=0))

    def _load_pose(self, scene, seq, frame):
        """Load 4x4 camera pose matrix."""
        path = os.path.join(self.dataset_root, scene, seq, f"pose_{frame}.txt")
        pose = np.loadtxt(path, dtype=np.float64)  # (4, 4)
        return torch.from_numpy(pose).float()

    def _compute_relative_pose(self, T_img, T_depth):
        """
        Compute relative pose: T_rel = T_img^(-1) @ T_depth.

        Returns:
            pose_7d: (7,) tensor [qw, qx, qy, qz, tx, ty, tz]
        """
        T_rel = torch.linalg.inv(T_img) @ T_depth  # (4, 4)

        # Extract rotation matrix and convert to quaternion
        R = T_rel[:3, :3]
        t = T_rel[:3, 3]

        # Manual quaternion extraction (Shepperd's method)
        # This avoids importing pose_utils at module level (circular dependency risk)
        trace = R[0, 0] + R[1, 1] + R[2, 2]

        if trace > 0:
            s = 0.5 / torch.sqrt(trace + 1.0)
            qw = 0.25 / s
            qx = (R[2, 1] - R[1, 2]) * s
            qy = (R[0, 2] - R[2, 0]) * s
            qz = (R[1, 0] - R[0, 1]) * s
        elif R[0, 0] > R[1, 1] and R[0, 0] > R[2, 2]:
            s = 2.0 * torch.sqrt(1.0 + R[0, 0] - R[1, 1] - R[2, 2])
            qw = (R[2, 1] - R[1, 2]) / s
            qx = 0.25 * s
            qy = (R[0, 1] + R[1, 0]) / s
            qz = (R[0, 2] + R[2, 0]) / s
        elif R[1, 1] > R[2, 2]:
            s = 2.0 * torch.sqrt(1.0 + R[1, 1] - R[0, 0] - R[2, 2])
            qw = (R[0, 2] - R[2, 0]) / s
            qx = (R[0, 1] + R[1, 0]) / s
            qy = 0.25 * s
            qz = (R[1, 2] + R[2, 1]) / s
        else:
            s = 2.0 * torch.sqrt(1.0 + R[2, 2] - R[0, 0] - R[1, 1])
            qw = (R[1, 0] - R[0, 1]) / s
            qx = (R[0, 2] + R[2, 0]) / s
            qy = (R[1, 2] + R[2, 1]) / s
            qz = 0.25 * s

        # Normalize quaternion
        quat = torch.stack([qw, qx, qy, qz])
        quat = quat / quat.norm()

        pose_7d = torch.cat([quat, t])  # (7,)
        return pose_7d

    def __getitem__(self, idx):
        sample = self.samples[idx]

        # Load image and depth
        img_ref = sample["image"]
        dep_ref = sample["depth"]

        image = self._load_image(img_ref["scene"], img_ref["seq"], img_ref["frame"])
        depth = self._load_depth(dep_ref["scene"], dep_ref["seq"], dep_ref["frame"])

        # Load absolute poses
        T_img = self._load_pose(img_ref["scene"], img_ref["seq"], img_ref["frame"])
        T_depth = self._load_pose(dep_ref["scene"], dep_ref["seq"], dep_ref["frame"])

        # Compute relative pose GT
        gt_pose = self._compute_relative_pose(T_img, T_depth)

        # Apply augmentation
        if self.augment:
            image, depth = self._augment(image, depth)

        return {
            "image": image,
            "depth": depth,
            "intrinsic_rgb": self.intrinsic_matrix.clone(),
            "intrinsic_depth": self.intrinsic_matrix.clone(),
            "gt_pose": gt_pose,
            "sample_id": sample["id"],
        }

    def _augment(self, image, depth):
        """Apply data augmentation (simple geometric + photometric)."""
        # Random horizontal flip
        if torch.rand(1).item() > 0.5:
            image = torch.flip(image, [-1])
            depth = torch.flip(depth, [-1])

        # Color jitter (brightness, contrast, saturation)
        if torch.rand(1).item() > 0.5:
            brightness = 0.8 + 0.4 * torch.rand(1).item()  # [0.8, 1.2]
            image = (image * brightness).clamp(0.0, 1.0)

        return image, depth


def get_dataloader(
    config_path: str,
    split: str = "train",
    batch_size: int = 4,
    num_workers: int = 4,
    shuffle: bool = None,
    augment: bool = None,
    image_size: tuple = None,
    depth_scale: float = None,
):
    """
    Create DataLoader for RAFT-Pose training.

    Args:
        config_path: Path to JSON config file
        split: 'train' or 'val'
        batch_size: Batch size
        num_workers: Number of data loading workers
        shuffle: Whether to shuffle (default: True for train, False for val)
        augment: Whether to augment (default: True for train, False for val)
        image_size: Override image size (H, W)
        depth_scale: Override depth scale

    Returns:
        DataLoader instance
    """
    if shuffle is None:
        shuffle = (split == "train")
    if augment is None:
        augment = (split == "train")

    dataset = SevenScenesDataset(
        config_path=config_path,
        split=split,
        image_size=image_size,
        depth_scale=depth_scale,
        augment=augment,
    )

    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=(split == "train"),
        persistent_workers=(num_workers > 0),
    )

    return dataloader


def get_multi_config_dataloader(
    config_paths,
    split="train",
    batch_size=4,
    num_workers=4,
    shuffle=None,
    augment=None,
    image_size=None,
):
    """
    Create DataLoader from multiple config files with unified image size.

    Each config can have its own image_size and camera_intrinsics.
    Images are resized to the target image_size and intrinsics are scaled accordingly.
    Datasets are concatenated using ConcatDataset.

    Args:
        config_paths: List of paths to JSON config files
        split: 'train' or 'val'
        batch_size: Batch size
        num_workers: Number of data loading workers
        shuffle: Whether to shuffle (default: True for train, False for val)
        augment: Whether to augment (default: True for train, False for val)
        image_size: Unified target image size (H, W). If None, each config uses its own size.

    Returns:
        DataLoader instance
    """
    if shuffle is None:
        shuffle = (split == "train")
    if augment is None:
        augment = (split == "train")

    datasets = []
    skipped = []
    for config_path in config_paths:
        try:
            ds = SevenScenesDataset(
                config_path=config_path,
                split=split,
                image_size=image_size,
                augment=augment,
            )
            datasets.append(ds)
        except ValueError as e:
            skipped.append((config_path, str(e)))

    if skipped:
        for path, reason in skipped:
            print(f"  [MultiConfig] Skipped {os.path.basename(path)}: {reason}")

    if not datasets:
        raise ValueError(f"No valid datasets found for split '{split}'")

    if len(datasets) == 1:
        combined = datasets[0]
    else:
        combined = ConcatDataset(datasets)
        print(f"[MultiConfig] Combined {len(datasets)} datasets, "
              f"total {len(combined)} samples ({split})")

    dataloader = DataLoader(
        combined,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=(split == "train"),
        persistent_workers=(num_workers > 0),
    )

    return dataloader


# ─── Quick Test ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys

    config_path = sys.argv[1] if len(sys.argv) > 1 else "configs/chess_train.json"

    print(f"Testing dataloader with config: {config_path}\n")

    # Test dataset directly (no import from raft_pose needed)
    ds = SevenScenesDataset(config_path, split="train")
    sample = ds[0]
    print(f"Sample 0:")
    print(f"  image:          {sample['image'].shape}, dtype={sample['image'].dtype}, "
          f"range=[{sample['image'].min():.3f}, {sample['image'].max():.3f}]")
    print(f"  depth:          {sample['depth'].shape}, dtype={sample['depth'].dtype}, "
          f"range=[{sample['depth'].min():.3f}, {sample['depth'].max():.3f}]")
    print(f"  intrinsic_rgb:  {sample['intrinsic_rgb'].shape}")
    print(f"  intrinsic_depth:{sample['intrinsic_depth'].shape}")
    print(f"  gt_pose:        {sample['gt_pose'].shape}, values={sample['gt_pose'].numpy()}")
    quat_norm = sample['gt_pose'][:4].norm().item()
    print(f"  quaternion norm: {quat_norm:.6f} (should be ~1.0)")
    print(f"  sample_id:      {sample['sample_id']}")

    # Test dataloader
    print(f"\nTesting DataLoader (batch_size=2)...")
    dl = get_dataloader(config_path, split="train", batch_size=2, num_workers=0)
    batch = next(iter(dl))
    print(f"  image batch:     {batch['image'].shape}")
    print(f"  depth batch:     {batch['depth'].shape}")
    print(f"  intrinsic_rgb:   {batch['intrinsic_rgb'].shape}")
    print(f"  intrinsic_depth: {batch['intrinsic_depth'].shape}")
    print(f"  gt_pose batch:   {batch['gt_pose'].shape}")
    print(f"  sample_ids:      {batch['sample_id'].tolist()}")

    # Validate quaternion norms
    quat_norms = batch['gt_pose'][:, :4].norm(dim=1)
    print(f"  quat norms:      {quat_norms.tolist()} (should all be ~1.0)")

    print("\n✅ DataLoader test passed!")
