#!/usr/bin/env python3
"""
RAFT-Pose Training Script.

Usage:
    conda run -n matr2d3d2 python train.py --config configs/chess_train.json --epochs 50

Reads a JSON config file (generated by scripts/generate_pairs.py), creates
DataLoader, RAFTPose model, PoseLoss, and runs the training loop with:
    - AdamW optimizer
    - CosineAnnealingLR scheduler
    - Gradient clipping
    - Checkpoint saving (best model + last model)
    - Console + optional TensorBoard logging
"""

import os
import sys
import time
import json
import argparse
import numpy as np
from pathlib import Path

import torch
import torch.nn as nn
from torch.utils.tensorboard import SummaryWriter

# Setup import path
RAFT_POSE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(RAFT_POSE_DIR))

from raft_pose import RAFTPose
from pose_loss import PoseLoss
from dataloader import get_dataloader


# ─── Utilities ────────────────────────────────────────────────────────────────

class AverageMeter:
    """Track running average of a metric."""

    def __init__(self, name=""):
        self.name = name
        self.reset()

    def reset(self):
        self.val = 0.0
        self.avg = 0.0
        self.sum = 0.0
        self.count = 0

    def update(self, val, n=1):
        self.val = val
        self.sum += val * n
        self.count += n
        self.avg = self.sum / self.count


def save_checkpoint(state, is_best, checkpoint_dir, filename="checkpoint.pth"):
    """Save training checkpoint."""
    checkpoint_dir = Path(checkpoint_dir)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    filepath = checkpoint_dir / filename
    torch.save(state, str(filepath))

    if is_best:
        best_path = checkpoint_dir / "model_best.pth"
        torch.save(state, str(best_path))
        print(f"  ★ Best model saved (val_loss={state['best_val_loss']:.6f})")


def load_checkpoint(filepath, model, optimizer=None, scheduler=None):
    """Load training checkpoint with backward compatibility."""
    checkpoint = torch.load(filepath, map_location="cpu")

    # Handle backward compatibility: old checkpoints stored corr_proj with
    # corr_dim = N * C_corr (concatenated samples), but new model uses
    # corr_dim = C_corr (per-sample). The only affected layer is
    # pose_update_net.corr_proj.0 (Conv2d).
    model_state = checkpoint["model_state_dict"]
    new_state = model.state_dict()

    mismatch_keys = []
    for k in model_state:
        if k in new_state and model_state[k].shape != new_state[k].shape:
            mismatch_keys.append((k, model_state[k].shape, new_state[k].shape))

    if mismatch_keys:
        print(f"  [Compatibility] Skipping {len(mismatch_keys)} mismatched layers:")
        for k, old_shape, new_shape in mismatch_keys:
            print(f"    {k}: checkpoint {old_shape} -> model {new_shape}")
        # Only load matching layers
        model_state = {k: v for k, v in model_state.items()
                       if k not in new_state or model_state[k].shape == new_state[k].shape}
        missing, unexpected = model.load_state_dict(model_state, strict=False)
        if missing:
            print(f"  [Compatibility] Uninitialized layers: {missing}")
    else:
        model.load_state_dict(model_state)

    if optimizer is not None and "optimizer_state_dict" in checkpoint:
        optimizer.load_state_dict(checkpoint["optimizer_state_dict"])

    if scheduler is not None and "scheduler_state_dict" in checkpoint:
        scheduler.load_state_dict(checkpoint["scheduler_state_dict"])

    return checkpoint


def build_model(args):
    """Build RAFTPose model from args/config."""
    model = RAFTPose(
        image_encoder=args.image_encoder,
        hidden_dim=args.hidden_dim,
        context_dim=args.context_dim,
        depth_dim=args.depth_dim,
        corr_levels=args.corr_levels,
        corr_radius=args.corr_radius,
        num_iterations=args.num_iterations,
        num_pose_samples=args.num_pose_samples,
        pose_sample_std=args.pose_sample_std,
        init_pose_noise_std=args.init_pose_noise_std,
    )
    return model


# ─── Training Loop ────────────────────────────────────────────────────────────

def train_one_epoch(model, dataloader, criterion, optimizer, device, epoch,
                    grad_clip=1.0, log_interval=10, grad_accum_steps=1,
                    seq_loss_gamma=0.8):
    """Train for one epoch with sequence loss and gradient accumulation."""
    model.train()

    loss_meter = AverageMeter("Loss")
    rot_meter = AverageMeter("Rot(deg)")
    trans_meter = AverageMeter("Trans(m)")
    data_time_meter = AverageMeter("Data")
    batch_time_meter = AverageMeter("Batch")

    end = time.time()
    optimizer.zero_grad()

    for i, batch in enumerate(dataloader):
        # Measure data loading time
        data_time_meter.update(time.time() - end)

        # Move to device
        image = batch["image"].to(device)
        depth = batch["depth"].to(device)
        intrinsic_rgb = batch["intrinsic_rgb"].to(device)
        intrinsic_depth = batch["intrinsic_depth"].to(device)
        gt_pose = batch["gt_pose"].to(device)

        # Initial pose: identity (assumes image and depth are aligned)
        # The model's job is to refine from this starting point toward GT relative pose
        B = image.size(0)
        init_pose = torch.cat([
            torch.ones(B, 1, device=device),   # qw = 1
            torch.zeros(B, 3, device=device),   # qx, qy, qz = 0
            torch.zeros(B, 3, device=device),   # tx, ty, tz = 0
        ], dim=1)  # (B, 7)

        # Forward — return all intermediate poses for sequence loss
        _, pose_sequence = model(
            image=image,
            depth=depth,
            intrinsic_rgb=intrinsic_rgb,
            intrinsic_depth=intrinsic_depth,
            init_pose=init_pose,
            return_all_poses=True,
        )

        # Sequence loss with exponential weighting
        loss, details = criterion.forward_sequence(
            pose_sequence, gt_pose, gamma=seq_loss_gamma
        )

        # Scale loss for gradient accumulation
        loss = loss / grad_accum_steps

        # Backward (accumulate gradients)
        loss.backward()

        # Optimizer step every grad_accum_steps
        if (i + 1) % grad_accum_steps == 0 or (i + 1) == len(dataloader):
            if grad_clip > 0:
                nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
            optimizer.step()
            optimizer.zero_grad()

        # Update meters
        loss_meter.update(details["total_loss"], image.size(0))
        rot_meter.update(details["rot_loss_deg"], image.size(0))
        trans_meter.update(details["trans_loss"], image.size(0))

        batch_time_meter.update(time.time() - end)
        end = time.time()

        # Console logging
        if (i + 1) % log_interval == 0 or (i + 1) == len(dataloader):
            print(
                f"  Epoch [{epoch}] Step [{i+1}/{len(dataloader)}]  "
                f"Loss: {loss_meter.avg:.4f}  "
                f"Rot: {rot_meter.avg:.2f}°  "
                f"Trans: {trans_meter.avg:.4f}m  "
                f"Data: {data_time_meter.avg:.3f}s  "
                f"Batch: {batch_time_meter.avg:.3f}s"
            )

    return {
        "train_loss": loss_meter.avg,
        "train_rot_deg": rot_meter.avg,
        "train_trans_m": trans_meter.avg,
    }


@torch.no_grad()
def validate(model, dataloader, criterion, device):
    """Run validation."""
    model.eval()

    loss_meter = AverageMeter("Loss")
    rot_meter = AverageMeter("Rot(deg)")
    trans_meter = AverageMeter("Trans(m)")

    for batch in dataloader:
        image = batch["image"].to(device)
        depth = batch["depth"].to(device)
        intrinsic_rgb = batch["intrinsic_rgb"].to(device)
        intrinsic_depth = batch["intrinsic_depth"].to(device)
        gt_pose = batch["gt_pose"].to(device)

        pred_pose = model(
            image=image,
            depth=depth,
            intrinsic_rgb=intrinsic_rgb,
            intrinsic_depth=intrinsic_depth,
        )

        loss, details = criterion(pred_pose, gt_pose)

        loss_meter.update(details["total_loss"], image.size(0))
        rot_meter.update(details["rot_loss_deg"], image.size(0))
        trans_meter.update(details["trans_loss"], image.size(0))

    return {
        "val_loss": loss_meter.avg,
        "val_rot_deg": rot_meter.avg,
        "val_trans_m": trans_meter.avg,
    }


# ─── Main ─────────────────────────────────────────────────────────────────────

def parse_args():
    parser = argparse.ArgumentParser(description="RAFT-Pose Training")

    # Data
    parser.add_argument("--config", type=str, required=True,
                        help="Path to JSON config file")
    parser.add_argument("--num_workers", type=int, default=4,
                        help="DataLoader workers")
    parser.add_argument("--image_size", type=int, nargs=2, default=None,
                        metavar=("H", "W"),
                        help="Override image size (H W). Recommended: 256 320")

    # Model architecture
    parser.add_argument("--image_encoder", type=str, default="basic",
                        choices=["basic", "small"])
    parser.add_argument("--hidden_dim", type=int, default=128)
    parser.add_argument("--context_dim", type=int, default=64)
    parser.add_argument("--depth_dim", type=int, default=32)
    parser.add_argument("--corr_levels", type=int, default=4)
    parser.add_argument("--corr_radius", type=int, default=4)
    parser.add_argument("--num_iterations", type=int, default=12)
    parser.add_argument("--num_pose_samples", type=int, default=16)
    parser.add_argument("--pose_sample_std", type=float, default=0.01)
    parser.add_argument("--init_pose_noise_std", type=float, default=0.05)

    # Training
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch_size", type=int, default=4)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--weight_decay", type=float, default=1e-5)
    parser.add_argument("--grad_clip", type=float, default=1.0)
    parser.add_argument("--grad_accum_steps", type=int, default=1,
                        help="Gradient accumulation steps (effective batch = batch_size * grad_accum_steps)")
    parser.add_argument("--seq_loss_gamma", type=float, default=0.8,
                        help="Exponential weighting for sequence loss. "
                             "Later iterations weighted more (1.0 = equal, 0.8 = last ~2.4x first for K=4)")
    parser.add_argument("--scheduler", type=str, default="cosine",
                        choices=["cosine", "step", "none"])

    # Loss weights
    parser.add_argument("--rot_weight", type=float, default=1.0,
                        help="Weight for rotation loss")
    parser.add_argument("--trans_weight", type=float, default=10.0,
                        help="Weight for translation loss")

    # Checkpointing
    parser.add_argument("--checkpoint_dir", type=str, default="checkpoints")
    parser.add_argument("--resume", type=str, default=None,
                        help="Path to checkpoint to resume from")

    # Logging
    parser.add_argument("--log_interval", type=int, default=10)
    parser.add_argument("--tensorboard", action="store_true",
                        help="Enable TensorBoard logging")
    parser.add_argument("--tb_dir", type=str, default="runs")

    # Device
    parser.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--seed", type=int, default=42)

    return parser.parse_args()


def main():
    args = parse_args()

    # Seed
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    device = torch.device(args.device)
    print(f"Device: {device}")
    print(f"Config: {args.config}")

    # ─── Data ─────────────────────────────────────────────────────────────
    train_loader = get_dataloader(
        args.config, split="train",
        batch_size=args.batch_size,
        num_workers=args.num_workers,
        image_size=tuple(args.image_size) if args.image_size else None,
        augment=False,
    )
    val_loader = get_dataloader(
        args.config, split="val",
        batch_size=args.batch_size,
        num_workers=args.num_workers,
        image_size=tuple(args.image_size) if args.image_size else None,
    )

    # ─── Model ────────────────────────────────────────────────────────────
    model = build_model(args).to(device)

    n_params = sum(p.numel() for p in model.parameters())
    n_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"Model parameters: {n_params:,} (trainable: {n_trainable:,})")

    # ─── Loss ─────────────────────────────────────────────────────────────
    criterion = PoseLoss(rot_weight=args.rot_weight, trans_weight=args.trans_weight)

    # ─── Optimizer & Scheduler ────────────────────────────────────────────
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )

    if args.scheduler == "cosine":
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=args.epochs, eta_min=args.lr * 0.01
        )
    elif args.scheduler == "step":
        scheduler = torch.optim.lr_scheduler.StepLR(
            optimizer, step_size=args.epochs // 3, gamma=0.1
        )
    else:
        scheduler = None

    # ─── Resume ───────────────────────────────────────────────────────────
    start_epoch = 1
    best_val_loss = float("inf")

    if args.resume:
        if os.path.isfile(args.resume):
            print(f"Resuming from checkpoint: {args.resume}")
            ckpt = load_checkpoint(args.resume, model, optimizer, scheduler)
            start_epoch = ckpt.get("epoch", 0) + 1
            best_val_loss = ckpt.get("best_val_loss", float("inf"))
            print(f"  Resumed at epoch {start_epoch}, best_val_loss={best_val_loss:.6f}")
        else:
            print(f"Warning: checkpoint not found at {args.resume}")

    # ─── TensorBoard ─────────────────────────────────────────────────────
    writer = None
    if args.tensorboard:
        config_name = Path(args.config).stem
        run_name = f"{config_name}_lr{args.lr}_bs{args.batch_size}"
        tb_log_dir = Path(args.tb_dir) / run_name
        writer = SummaryWriter(log_dir=str(tb_log_dir))
        print(f"TensorBoard logging to: {tb_log_dir}")

    # ─── Training Loop ────────────────────────────────────────────────────
    print(f"\n{'='*60}")
    print(f"Training: {args.epochs} epochs, batch_size={args.batch_size}, lr={args.lr}")
    print(f"{'='*60}\n")

    for epoch in range(start_epoch, args.epochs + 1):
        print(f"Epoch {epoch}/{args.epochs}  (lr={optimizer.param_groups[0]['lr']:.2e})")

        # Train
        train_metrics = train_one_epoch(
            model, train_loader, criterion, optimizer, device, epoch,
            grad_clip=args.grad_clip, log_interval=args.log_interval,
            grad_accum_steps=args.grad_accum_steps,
            seq_loss_gamma=args.seq_loss_gamma,
        )

        # Validate
        val_metrics = validate(model, val_loader, criterion, device)

        # Scheduler step
        if scheduler is not None:
            scheduler.step()

        # Logging
        print(
            f"  Train → Loss: {train_metrics['train_loss']:.4f}  "
            f"Rot: {train_metrics['train_rot_deg']:.2f}°  "
            f"Trans: {train_metrics['train_trans_m']:.4f}m"
        )
        print(
            f"  Val   → Loss: {val_metrics['val_loss']:.4f}  "
            f"Rot: {val_metrics['val_rot_deg']:.2f}°  "
            f"Trans: {val_metrics['val_trans_m']:.4f}m"
        )

        # TensorBoard
        if writer is not None:
            for k, v in train_metrics.items():
                writer.add_scalar(k, v, epoch)
            for k, v in val_metrics.items():
                writer.add_scalar(k, v, epoch)
            writer.add_scalar("lr", optimizer.param_groups[0]["lr"], epoch)

        # Checkpoint
        is_best = val_metrics["val_loss"] < best_val_loss
        best_val_loss = min(val_metrics["val_loss"], best_val_loss)

        save_checkpoint(
            {
                "epoch": epoch,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "scheduler_state_dict": scheduler.state_dict() if scheduler else None,
                "best_val_loss": best_val_loss,
                "train_metrics": train_metrics,
                "val_metrics": val_metrics,
                "args": vars(args),
            },
            is_best=is_best,
            checkpoint_dir=args.checkpoint_dir,
        )

        print()

    # ─── Cleanup ──────────────────────────────────────────────────────────
    if writer is not None:
        writer.close()

    print(f"Training complete. Best val_loss: {best_val_loss:.6f}")
    print(f"Checkpoints saved to: {args.checkpoint_dir}")


if __name__ == "__main__":
    main()
