#!/usr/bin/env python3
"""
RAFT-Pose Training Script.

Usage:
    conda run -n matr2d3d2 python train.py --config configs/chess_train.json --epochs 50

Reads a JSON config file (generated by scripts/generate_pairs.py), creates
DataLoader, RAFTPose model, PoseLoss, and runs the training loop with:
    - AdamW optimizer
    - CosineAnnealingLR scheduler
    - Gradient clipping
    - Checkpoint saving (best model + last model)
    - Console + optional TensorBoard logging
"""

import os
import sys
import time
import json
import argparse
import numpy as np
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.tensorboard import SummaryWriter

# Setup import path
RAFT_POSE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(RAFT_POSE_DIR))

from raft_pose import RAFTPose
from pose_loss import PoseLoss, DeltaPoseLoss
from dataloader import get_dataloader


# ─── Utilities ────────────────────────────────────────────────────────────────

def get_next_run_dir(base_dir="checkpoints", prefix="runs"):
    """
    Determine the next available run directory under base_dir.
    
    Scans existing `{prefix}_*` folders and increments the counter.
    Returns (run_dir_path, run_number).
    """
    base = Path(base_dir)
    base.mkdir(parents=True, exist_ok=True)
    
    existing = [d.name for d in base.iterdir() if d.is_dir() and d.name.startswith(prefix + "_")]
    max_n = 0
    for name in existing:
        try:
            n = int(name.split("_")[-1])
            max_n = max(max_n, n)
        except ValueError:
            continue
    
    next_n = max_n + 1
    run_dir = base / f"{prefix}_{next_n:03d}"
    run_dir.mkdir(parents=True, exist_ok=True)
    return str(run_dir), next_n


class AverageMeter:
    """Track running average of a metric."""

    def __init__(self, name=""):
        self.name = name
        self.reset()

    def reset(self):
        self.val = 0.0
        self.avg = 0.0
        self.sum = 0.0
        self.count = 0

    def update(self, val, n=1):
        self.val = val
        self.sum += val * n
        self.count += n
        self.avg = self.sum / self.count


def save_checkpoint(state, is_best, checkpoint_dir, filename="checkpoint.pth"):
    """Save training checkpoint."""
    checkpoint_dir = Path(checkpoint_dir)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    filepath = checkpoint_dir / filename
    torch.save(state, str(filepath))

    if is_best:
        best_path = checkpoint_dir / "model_best.pth"
        torch.save(state, str(best_path))
        print(f"  ★ Best model saved (val_loss={state['best_val_loss']:.6f})")


def load_checkpoint(filepath, model, optimizer=None, scheduler=None):
    """Load training checkpoint with backward compatibility."""
    checkpoint = torch.load(filepath, map_location="cpu")

    # Handle backward compatibility: old checkpoints stored corr_proj with
    # corr_dim = N * C_corr (concatenated samples), but new model uses
    # corr_dim = C_corr (per-sample). The only affected layer is
    # pose_update_net.corr_proj.0 (Conv2d).
    model_state = checkpoint["model_state_dict"]
    new_state = model.state_dict()

    mismatch_keys = []
    for k in model_state:
        if k in new_state and model_state[k].shape != new_state[k].shape:
            mismatch_keys.append((k, model_state[k].shape, new_state[k].shape))

    if mismatch_keys:
        print(f"  [Compatibility] Skipping {len(mismatch_keys)} mismatched layers:")
        for k, old_shape, new_shape in mismatch_keys:
            print(f"    {k}: checkpoint {old_shape} -> model {new_shape}")
        # Only load matching layers
        model_state = {k: v for k, v in model_state.items()
                       if k not in new_state or model_state[k].shape == new_state[k].shape}
        missing, unexpected = model.load_state_dict(model_state, strict=False)
        if missing:
            print(f"  [Compatibility] Uninitialized layers: {missing}")
    else:
        # Filter out unexpected keys (e.g., runtime caches like corr_block._cached_*)
        unexpected_keys = [k for k in model_state if k not in new_state]
        if unexpected_keys:
            print(f"  [Compatibility] Filtering {len(unexpected_keys)} unexpected keys:")
            for k in unexpected_keys:
                print(f"    {k}")
            model_state = {k: v for k, v in model_state.items() if k in new_state}
        model.load_state_dict(model_state)

    if optimizer is not None and "optimizer_state_dict" in checkpoint:
        optimizer.load_state_dict(checkpoint["optimizer_state_dict"])

    if scheduler is not None and "scheduler_state_dict" in checkpoint:
        scheduler.load_state_dict(checkpoint["scheduler_state_dict"])

    return checkpoint


def build_model(args):
    """Build RAFTPose model from args/config."""
    model = RAFTPose(
        image_encoder=args.image_encoder,
        hidden_dim=args.hidden_dim,
        context_dim=args.context_dim,
        depth_dim=args.depth_dim,
        corr_levels=args.corr_levels,
        corr_radius=args.corr_radius,
        num_iterations=args.num_iterations,
        pose_sample_std=args.pose_sample_std,
        init_pose_noise_std=args.init_pose_noise_std,
        use_checkpoint=getattr(args, 'use_checkpoint', False),
        use_amp=getattr(args, 'use_amp', False),
        coarse_to_fine=getattr(args, 'coarse_to_fine', False),
        corr_temperature=getattr(args, 'corr_temperature', 1.0),
        max_rot_step=getattr(args, 'max_rot_step', 0.3),
        max_trans_step=getattr(args, 'max_trans_step', 0.3),
        shared_encoder=getattr(args, 'shared_encoder', False),
    )
    return model


# ─── Training Loop ────────────────────────────────────────────────────────────

def train_one_epoch(model, dataloader, criterion, optimizer, device, epoch,
                    grad_clip=1.0, log_interval=10, grad_accum_steps=1,
                    seq_loss_gamma=0.8, total_epochs=100,
                    curriculum_start=0.01, curriculum_end=0.1,
                    curriculum_warmup=0.8,
                    delta_criterion=None, delta_loss_weight=1.0):
    """Train for one epoch with sequence loss and gradient accumulation."""
    model.train()

    loss_meter = AverageMeter("Loss")
    rot_meter = AverageMeter("Rot(deg)")
    trans_meter = AverageMeter("Trans(m)")
    data_time_meter = AverageMeter("Data")
    batch_time_meter = AverageMeter("Batch")

    end = time.time()
    optimizer.zero_grad()

    for i, batch in enumerate(dataloader):
        # Measure data loading time
        data_time_meter.update(time.time() - end)

        # Move to device
        image = batch["image"].to(device)
        depth = batch["depth"].to(device)
        intrinsic_rgb = batch["intrinsic_rgb"].to(device)
        intrinsic_depth = batch["intrinsic_depth"].to(device)
        gt_pose = batch["gt_pose"].to(device)

        # Curriculum learning: initial pose from GT + noise
        # Noise level increases linearly from curriculum_start to curriculum_end
        # over the first curriculum_warmup_fraction of total epochs.
        # This lets the model first learn small refinements, then progressively
        # handle larger initial pose errors.
        B = image.size(0)
        gt_quat = gt_pose[:, :4]   # (B, 4)
        gt_trans = gt_pose[:, 4:7]  # (B, 3)

        # Compute current noise level from curriculum schedule
        progress = min(1.0, (epoch - 1) / max(1, total_epochs * curriculum_warmup))
        noise_level = curriculum_start + (curriculum_end - curriculum_start) * progress

        # Add noise to GT quaternion: small angular perturbation
        quat_noise = torch.randn(B, 3, device=device) * noise_level
        # Convert small angle noise to quaternion delta via Rodrigues
        noise_angles = quat_noise.norm(dim=1, keepdim=True)
        noise_angles_clamped = noise_angles.clamp(max=3.1415926)
        sin_na = torch.sin(noise_angles_clamped / 2.0)
        cos_na = torch.cos(noise_angles_clamped / 2.0)
        noise_axes = quat_noise / noise_angles.clamp(min=1e-8)
        dq_noise = torch.cat([cos_na, noise_axes * sin_na], dim=1)  # (B, 4)
        # Handle near-zero noise
        tiny_mask = (noise_angles < 1e-6).expand_as(dq_noise)
        dq_identity = torch.zeros_like(dq_noise)
        dq_identity[:, 0] = 1.0
        dq_noise = torch.where(tiny_mask, dq_identity, dq_noise)

        # Compose: init_quat = gt_quat * dq_noise
        w1, x1, y1, z1 = gt_quat[:, 0], gt_quat[:, 1], gt_quat[:, 2], gt_quat[:, 3]
        w2, x2, y2, z2 = dq_noise[:, 0], dq_noise[:, 1], dq_noise[:, 2], dq_noise[:, 3]
        init_quat = torch.stack([
            w1*w2 - x1*x2 - y1*y2 - z1*z2,
            w1*x2 + x1*w2 + y1*z2 - z1*y2,
            w1*y2 - x1*z2 + y1*w2 + z1*x2,
            w1*z2 + x1*y2 - y1*x2 + z1*w2,
        ], dim=1)
        init_quat = F.normalize(init_quat, dim=1)

        # Add noise to GT translation
        trans_noise = torch.randn(B, 3, device=device) * noise_level
        init_trans = gt_trans + trans_noise

        init_pose = torch.cat([init_quat, init_trans], dim=1)  # (B, 7)

        # Forward — return all intermediate poses AND deltas for sequence loss
        # AMP autocast is handled inside the model (encoder-only), no need here
        _, extra = model(
            image=image,
            depth=depth,
            intrinsic_rgb=intrinsic_rgb,
            intrinsic_depth=intrinsic_depth,
            init_pose=init_pose,
            return_all_poses=True,
            return_all_deltas=True,
        )
        pose_sequence = extra['pose_sequence']
        delta_sequence = extra['delta_sequence']

        # Sequence loss with exponential weighting (end-pose supervision)
        loss, details = criterion.forward_sequence(
            pose_sequence, gt_pose, gamma=seq_loss_gamma
        )

        # Delta supervision loss (direct delta guidance)
        if delta_criterion is not None and delta_loss_weight > 0:
            delta_loss, delta_details = delta_criterion(
                delta_sequence, pose_sequence, gt_pose, gamma=seq_loss_gamma
            )
            loss = loss + delta_loss_weight * delta_loss

        # NaN / Inf guard: skip batch if loss is degenerate
        if not torch.isfinite(loss):
            if (i + 1) % log_interval == 0:
                print(f"  Epoch [{epoch}] Step [{i+1}/{len(dataloader)}]  ⚠ NaN/Inf loss, skipping batch")
            optimizer.zero_grad()
            end = time.time()
            continue

        # Scale loss for gradient accumulation
        loss = loss / grad_accum_steps

        # Backward (accumulate gradients)
        loss.backward()

        # Optimizer step every grad_accum_steps
        if (i + 1) % grad_accum_steps == 0 or (i + 1) == len(dataloader):
            if grad_clip > 0:
                nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
            # Check for NaN in gradients before stepping
            has_nan_grad = False
            for p in model.parameters():
                if p.grad is not None and not torch.isfinite(p.grad).all():
                    has_nan_grad = True
                    break
            if has_nan_grad:
                if (i + 1) % log_interval == 0:
                    print(f"  Epoch [{epoch}] Step [{i+1}/{len(dataloader)}]  ⚠ NaN in gradients, skipping optimizer step")
                optimizer.zero_grad()
            else:
                optimizer.step()
                optimizer.zero_grad()

        # Update meters
        loss_meter.update(details["total_loss"], image.size(0))
        rot_meter.update(details["rot_loss_deg"], image.size(0))
        trans_meter.update(details["trans_loss"], image.size(0))

        batch_time_meter.update(time.time() - end)
        end = time.time()

        # Console logging
        if (i + 1) % log_interval == 0 or (i + 1) == len(dataloader):
            print(
                f"  Epoch [{epoch}] Step [{i+1}/{len(dataloader)}]  "
                f"Loss: {loss_meter.avg:.4f}  "
                f"Rot: {rot_meter.avg:.2f}°  "
                f"Trans: {trans_meter.avg:.4f}m  "
                f"Data: {data_time_meter.avg:.3f}s  "
                f"Batch: {batch_time_meter.avg:.3f}s"
            )

    return {
        "train_loss": loss_meter.avg,
        "train_rot_deg": rot_meter.avg,
        "train_trans_m": trans_meter.avg,
    }


@torch.no_grad()
def validate(model, dataloader, criterion, device):
    """Run validation."""
    model.eval()

    loss_meter = AverageMeter("Loss")
    rot_meter = AverageMeter("Rot(deg)")
    trans_meter = AverageMeter("Trans(m)")

    for batch in dataloader:
        image = batch["image"].to(device)
        depth = batch["depth"].to(device)
        intrinsic_rgb = batch["intrinsic_rgb"].to(device)
        intrinsic_depth = batch["intrinsic_depth"].to(device)
        gt_pose = batch["gt_pose"].to(device)

        result = model(
            image=image,
            depth=depth,
            intrinsic_rgb=intrinsic_rgb,
            intrinsic_depth=intrinsic_depth,
        )

        # Handle both old format (tensor) and new format (tensor, dict)
        if isinstance(result, tuple):
            pred_pose = result[0]
        else:
            pred_pose = result

        loss, details = criterion(pred_pose, gt_pose)

        loss_meter.update(details["total_loss"], image.size(0))
        rot_meter.update(details["rot_loss_deg"], image.size(0))
        trans_meter.update(details["trans_loss"], image.size(0))

    return {
        "val_loss": loss_meter.avg,
        "val_rot_deg": rot_meter.avg,
        "val_trans_m": trans_meter.avg,
    }


# ─── Main ─────────────────────────────────────────────────────────────────────

def parse_args():
    parser = argparse.ArgumentParser(description="RAFT-Pose Training")

    # Data
    parser.add_argument("--config", type=str, required=True,
                        help="Path to JSON config file")
    parser.add_argument("--num_workers", type=int, default=4,
                        help="DataLoader workers")
    parser.add_argument("--image_size", type=int, nargs=2, default=None,
                        metavar=("H", "W"),
                        help="Override image size (H W). Recommended: 256 320")

    # Model architecture
    parser.add_argument("--image_encoder", type=str, default="basic",
                        choices=["basic", "small", "resnet18"])
    parser.add_argument("--shared_encoder", action="store_true",
                        help="Use same encoder for RGB and depth (Siamese). "
                             "Depth is repeated to 3 channels. No separate depth encoder.")
    parser.add_argument("--hidden_dim", type=int, default=128)
    parser.add_argument("--context_dim", type=int, default=64)
    parser.add_argument("--depth_dim", type=int, default=32)
    parser.add_argument("--corr_levels", type=int, default=4)
    parser.add_argument("--corr_radius", type=int, default=4)
    parser.add_argument("--num_iterations", type=int, default=6)
    parser.add_argument("--pose_sample_std", type=float, default=0.05)
    parser.add_argument("--init_pose_noise_std", type=float, default=0.00)

    # Training
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch_size", type=int, default=4)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--weight_decay", type=float, default=1e-5)
    parser.add_argument("--grad_clip", type=float, default=1.0)
    parser.add_argument("--grad_accum_steps", type=int, default=1,
                        help="Gradient accumulation steps (effective batch = batch_size * grad_accum_steps)")
    parser.add_argument("--seq_loss_gamma", type=float, default=0.8,
                        help="Exponential weighting for sequence loss. "
                             "Later iterations weighted more (1.0 = equal, 0.8 = last ~2.4x first for K=4)")
    parser.add_argument("--scheduler", type=str, default="cosine",
                        choices=["cosine", "step", "none"])

    # Loss weights
    parser.add_argument("--rot_weight", type=float, default=100.0,
                        help="Weight for rotation loss (in degrees via rad-to-deg scaling)")
    parser.add_argument("--trans_weight", type=float, default=20.0,
                        help="Weight for translation loss (in meters)")

    # Curriculum learning
    parser.add_argument("--curriculum_start", type=float, default=0.1,
                        help="Initial noise level for curriculum learning (rad/m). "
                             "~0.01 = 0.57° / 1cm — model starts near GT.")
    parser.add_argument("--curriculum_end", type=float, default=0.5,
                        help="Final noise level for curriculum learning (rad/m). "
                             "~0.2 = 11.5° / 20cm — model handles large errors.")
    parser.add_argument("--curriculum_warmup", type=float, default=0.8,
                        help="Fraction of total epochs over which noise ramps up. "
                             "0.8 = noise reaches max at 80%% of training.")

    # Checkpointing
    parser.add_argument("--checkpoint_dir", type=str, default="checkpoints")
    parser.add_argument("--resume", type=str, default=None,
                        help="Path to checkpoint to resume from")

    # Logging
    parser.add_argument("--log_interval", type=int, default=10)
    parser.add_argument("--tensorboard", action="store_true",
                        help="Enable TensorBoard logging")
    parser.add_argument("--tb_dir", type=str, default="runs")

    # Device
    parser.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--seed", type=int, default=42)

    # Memory optimization
    parser.add_argument("--use_amp", action="store_true",
                        help="Enable Automatic Mixed Precision (float16) for ~40%% memory reduction")
    parser.add_argument("--use_checkpoint", action="store_true",
                        help="Enable gradient checkpointing on encoders for ~50%% activation memory reduction")
    parser.add_argument("--coarse_to_fine", action="store_true",
                        help="Use coarse-to-fine correlation sampling: evaluate all N samples on "
                             "coarsest pyramid level first, then full multi-level sampling on top-K only. "
                             "Reduces peak memory from O(B*N) to O(B*K) for fine sampling.")
    parser.add_argument("--corr_temperature", type=float, default=1.0,
                        help="Correlation volume temperature. 1.0=raw cosine similarity. "
                             ">1.0=smoother landscape (recommended for ResNet18: 2.0-5.0). "
                             "Smooths sharp correlation peaks to prevent PoseUpdateNet overshooting.")
    parser.add_argument("--max_rot_step", type=float, default=0.3,
                        help="Maximum rotation step per iteration in radians. "
                             "Clamps predicted rot_vec to [-max_rot_step, max_rot_step]. "
                             "Prevents overshooting. Default: 0.3 rad (≈17°).")
    parser.add_argument("--max_trans_step", type=float, default=0.3,
                        help="Maximum translation step per iteration in meters. "
                             "Clamps predicted dt to [-max_trans_step, max_trans_step]. "
                             "Prevents overshooting. Default: 0.3 m.")
    parser.add_argument("--delta_loss_weight", type=float, default=1.0,
                        help="Weight for delta pose supervision loss. 0 to disable. "
                             "Directly supervises the predicted (rot_vec, dt) against the true delta. "
                             "Recommended: 1.0-10.0")
    parser.add_argument("--pretrained_encoder", type=str, default=None,
                        help="Path to pretrained encoder checkpoint (from pretrain_encoder.py). "
                             "Loads image_encoder, depth_encoder, depth_feat_align weights.")
    parser.add_argument("--freeze_encoder_epochs", type=int, default=0,
                        help="Freeze encoder for first N epochs during end-to-end training. "
                             "0 = no freezing. Recommended: 2-5 epochs after pretraining.")
    parser.add_argument("--resume_model_only", action="store_true",
                        help="Only load model weights from checkpoint, ignore optimizer/scheduler/epoch. "
                             "Useful when you want to change lr, epochs, or scheduler after resuming.")

    return parser.parse_args()


def main():
    args = parse_args()

    # Seed
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    device = torch.device(args.device)
    print(f"Device: {device}")
    print(f"Config: {args.config}")

    # ─── Run directory ────────────────────────────────────────────────────
    run_dir, run_n = get_next_run_dir(args.checkpoint_dir, prefix="runs")
    log_path = Path(run_dir) / "train_log.txt"
    print(f"Run directory: {run_dir}")

    def log_print(msg, also_stdout=True):
        """Print to both console and log file."""
        line = msg + "\n"
        if also_stdout:
            print(msg, flush=True)
        with open(log_path, "a") as f:
            f.write(line)

    log_print(f"Device: {device}")
    log_print(f"Config: {args.config}")
    log_print(f"Run directory: {run_dir}")
    log_print(f"Arguments: {json.dumps(vars(args), indent=2)}")

    # ─── Data ─────────────────────────────────────────────────────────────
    train_loader = get_dataloader(
        args.config, split="train",
        batch_size=args.batch_size,
        num_workers=args.num_workers,
        image_size=tuple(args.image_size) if args.image_size else None,
        augment=False,
    )
    val_loader = get_dataloader(
        args.config, split="val",
        batch_size=args.batch_size,
        num_workers=args.num_workers,
        image_size=tuple(args.image_size) if args.image_size else None,
    )

    # ─── Model ────────────────────────────────────────────────────────────
    model = build_model(args).to(device)

    n_params = sum(p.numel() for p in model.parameters())
    n_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"Model parameters: {n_params:,} (trainable: {n_trainable:,})")

    # ─── Loss ─────────────────────────────────────────────────────────────
    criterion = PoseLoss(rot_weight=args.rot_weight, trans_weight=args.trans_weight)
    delta_criterion = DeltaPoseLoss(rot_weight=args.rot_weight, trans_weight=args.trans_weight)
    delta_loss_weight = getattr(args, 'delta_loss_weight', 1.0)
    if delta_loss_weight > 0:
        log_print(f"Delta supervision loss enabled (weight={delta_loss_weight})")

    # ─── Optimizer & Scheduler ────────────────────────────────────────────
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )

    if args.scheduler == "cosine":
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=args.epochs, eta_min=args.lr * 0.01
        )
    elif args.scheduler == "step":
        scheduler = torch.optim.lr_scheduler.StepLR(
            optimizer, step_size=args.epochs // 3, gamma=0.1
        )
    else:
        scheduler = None

    # ─── Pretrained Encoder ────────────────────────────────────────────────
    if getattr(args, 'pretrained_encoder', None):
        pretrain_path = args.pretrained_encoder
        if os.path.isfile(pretrain_path):
            log_print(f"Loading pretrained encoder from: {pretrain_path}")
            pretrain_ckpt = torch.load(pretrain_path, map_location="cpu")
            pretrain_state = pretrain_ckpt.get("model_state_dict", pretrain_ckpt)
            # Only load encoder-related weights
            encoder_state = {k: v for k, v in pretrain_state.items()
                             if any(k.startswith(p) for p in
                                    ['image_encoder', 'depth_encoder', 'depth_feat_align'])}
            missing, unexpected = model.load_state_dict(encoder_state, strict=False)
            log_print(f"  Loaded {len(encoder_state)} encoder params")
            if missing:
                non_encoder_missing = [k for k in missing
                                       if not any(k.startswith(p) for p in
                                                  ['image_encoder', 'depth_encoder', 'depth_feat_align'])]
                if non_encoder_missing:
                    log_print(f"  Non-encoder missing (expected): {len(non_encoder_missing)} layers")
            if unexpected:
                log_print(f"  Unexpected keys: {unexpected}")
            log_print(f"  ★ Pretrained encoder loaded successfully")
        else:
            log_print(f"Warning: pretrained encoder not found at {pretrain_path}")

    # ─── Resume ───────────────────────────────────────────────────────────
    start_epoch = 1
    best_val_loss = float("inf")

    if args.resume:
        if os.path.isfile(args.resume):
            if getattr(args, 'resume_model_only', False):
                # Only load model weights, start fresh with optimizer/scheduler/epoch
                print(f"Loading model weights from: {args.resume} (model only, no optimizer/scheduler)")
                ckpt = load_checkpoint(args.resume, model, optimizer=None, scheduler=None)
                log_print(f"  Model weights loaded (model-only mode, starting from epoch 1)")
            else:
                print(f"Resuming from checkpoint: {args.resume}")
                ckpt = load_checkpoint(args.resume, model, optimizer, scheduler)
                start_epoch = ckpt.get("epoch", 0) + 1
                best_val_loss = ckpt.get("best_val_loss", float("inf"))
                print(f"  Resumed at epoch {start_epoch}, best_val_loss={best_val_loss:.6f}")
        else:
            print(f"Warning: checkpoint not found at {args.resume}")

    # ─── TensorBoard ─────────────────────────────────────────────────────
    writer = None
    if args.tensorboard:
        tb_log_dir = Path(run_dir) / "tensorboard"
        writer = SummaryWriter(log_dir=str(tb_log_dir))
        log_print(f"TensorBoard logging to: {tb_log_dir}")

    # ─── Training Loop ────────────────────────────────────────────────────
    if getattr(args, 'use_amp', False):
        log_print("AMP (float16 encoders) enabled")
    if getattr(args, 'use_checkpoint', False):
        log_print("Gradient checkpointing enabled")
    log_print(f"\n{'='*60}")
    log_print(f"Training: {args.epochs} epochs, batch_size={args.batch_size}, lr={args.lr}")
    log_print(f"{'='*60}\n")

    freeze_encoder_epochs = getattr(args, 'freeze_encoder_epochs', 0)

    for epoch in range(start_epoch, args.epochs + 1):
        # Freeze encoder for first N epochs if requested
        if freeze_encoder_epochs > 0:
            for name, param in model.named_parameters():
                if any(k in name for k in ['image_encoder', 'depth_encoder', 'depth_feat_align']):
                    param.requires_grad = (epoch > freeze_encoder_epochs)
            if epoch <= freeze_encoder_epochs:
                log_print(f"  [Epoch {epoch}] Encoder FROZEN (unfreeze after epoch {freeze_encoder_epochs})")
            elif epoch == freeze_encoder_epochs + 1:
                log_print(f"  [Epoch {epoch}] Encoder UNFROZEN — now training end-to-end")

        # Train
        train_metrics = train_one_epoch(
            model, train_loader, criterion, optimizer, device, epoch,
            grad_clip=args.grad_clip, log_interval=args.log_interval,
            grad_accum_steps=args.grad_accum_steps,
            seq_loss_gamma=args.seq_loss_gamma,
            total_epochs=args.epochs,
            curriculum_start=args.curriculum_start,
            curriculum_end=args.curriculum_end,
            curriculum_warmup=args.curriculum_warmup,
            delta_criterion=delta_criterion,
            delta_loss_weight=delta_loss_weight,
        )

        # Validate
        val_metrics = validate(model, val_loader, criterion, device)

        # Scheduler step
        if scheduler is not None:
            scheduler.step()

        # Logging
        # Compute current curriculum noise level for display
        cur_progress = min(1.0, (epoch - 1) / max(1, args.epochs * args.curriculum_warmup))
        cur_noise = args.curriculum_start + (args.curriculum_end - args.curriculum_start) * cur_progress
        log_print(
            f"Epoch [{epoch}/{args.epochs}] (lr={optimizer.param_groups[0]['lr']:.2e}, noise={cur_noise:.3f})"
        )
        log_print(
            f"  Train → Loss: {train_metrics['train_loss']:.4f}  "
            f"Rot: {train_metrics['train_rot_deg']:.2f}°  "
            f"Trans: {train_metrics['train_trans_m']:.4f}m"
        )
        log_print(
            f"  Val   → Loss: {val_metrics['val_loss']:.4f}  "
            f"Rot: {val_metrics['val_rot_deg']:.2f}°  "
            f"Trans: {val_metrics['val_trans_m']:.4f}m"
        )

        # TensorBoard
        if writer is not None:
            for k, v in train_metrics.items():
                writer.add_scalar(k, v, epoch)
            for k, v in val_metrics.items():
                writer.add_scalar(k, v, epoch)
            writer.add_scalar("lr", optimizer.param_groups[0]["lr"], epoch)

        # Checkpoint
        is_best = val_metrics["val_loss"] < best_val_loss
        best_val_loss = min(val_metrics["val_loss"], best_val_loss)

        save_checkpoint(
            {
                "epoch": epoch,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "scheduler_state_dict": scheduler.state_dict() if scheduler else None,
                "best_val_loss": best_val_loss,
                "train_metrics": train_metrics,
                "val_metrics": val_metrics,
                "args": vars(args),
            },
            is_best=is_best,
            checkpoint_dir=run_dir,
        )

        log_print("")

    # ─── Cleanup ──────────────────────────────────────────────────────────
    if writer is not None:
        writer.close()

    log_print(f"Training complete. Best val_loss: {best_val_loss:.6f}")
    log_print(f"Checkpoints saved to: {run_dir}")


if __name__ == "__main__":
    main()
